export { Home } from "./Home";
export { LandingPage } from "./LandingPage";
export { NotFound } from "./NotFound";
export { Places } from "./Places";
export { Account } from "./Account";
export { Favorites } from "./Favorites";
export { PlacesPrivate } from  "./PlacesPrivate";
export { MyPlaces } from "./MyPlaces";
export { About } from "./About";
